spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/exception_management?current_schema=main
    username: postgres
    password: 19801980
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
bot:
  username: Exception_managerbot
  token: 5415772343:AAEI8404yPyfP1z-fCh1iazh10SY0lngdgo
server:
  port: 6060
springdoc:
  swagger-ui:
    path: /sw
  api-docs:
    path: /api-docs

