spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54321/postgres?current_schema=main
    username: *****
    password: *******
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
bot:
  username: *********
  token: ************
server:
  port: 6060
springdoc:
  swagger-ui:
    path: /sw
  api-docs:
    path: /api-docs
file:
  root: C:\Users\Muhammaddiyor\IdeaProjects\ExceptionManagerBot\src\main\resources\sendFile
